### ISSUE TITLE
Add solutions to Backtracking Problems

### ISSUE THREAD

**Issue by vaishali614** [vaishali614/Coding-Interview-Preparation#2]
[Backtracking Problems](https://github.com/vaishali614/Coding-Interview-Preparation/tree/master/Day%209%20-%20Backtracking)

Guidelines:
1. Language - C++
2. Kindly use camelCase naming convention and proper numbering.
Example - 1. firstCode.cpp

**Comment by harsh1206** [comment]
Hi, can i write the code for Rat in a maze problem ?

**Comment by vaishali614** [comment]
@harsh1206 Sure. Assigned to you.
