### ISSUE TITLE
Add solutions to Mixed Problems

### ISSUE THREAD

**Issue by vaishali614** [vaishali614/Coding-Interview-Preparation#3]
[Mixed Problems](https://github.com/vaishali614/Coding-Interview-Preparation/tree/master/Day%2010%20-%20Mixed%20Problems)

Guidelines:
1. Language - C++
2. Kindly use camelCase naming convention and proper numbering.
Example - 1. firstCode.cpp

**Comment by daviduster** [comment]
Hey, can I take Subset Sum?

**Comment by vaishali614** [comment]
@daviduster Sure. Issue assigned to you.

**Comment by jayaganeshkumar** [comment]
@vaishali614  I wrote the code for Subset sum in java. Can you assign it to me?

**Comment by vaishali614** [comment]
@jayaganeshkumar No. This repository contains only C++ codes.

**Comment by jayaganeshkumar** [comment]
@vaishali614  ok
